// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function show(prim) {
  return prim;
}

var render = React.createElement("footer", {
      className: "page-footer teal"
    }, React.createElement("div", {
          className: "container"
        }, React.createElement("div", {
              className: "row"
            }, React.createElement("h5", {
                  className: "white-text"
                }, "Find me on:"), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                          className: "white-text",
                          href: "https://github.com/stevenmatthewt"
                        }, "GitHub")), React.createElement("li", undefined, React.createElement("a", {
                          className: "white-text",
                          href: "https://www.linkedin.com/in/steven-thomas-4a16458a/"
                        }, "LinkedIn"))))), React.createElement("div", {
          className: "footer-copyright"
        }, React.createElement("div", {
              className: "container"
            }, "Made with ", React.createElement("a", {
                  className: "brown-text text-lighten-3",
                  href: "http://materializecss.com"
                }, "Materialize"))));

exports.show = show;
exports.render = render;
/* render Not a pure module */
