// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Footer$ReactTemplate = require("./Footer.bs.js");
var Navigation$ReactTemplate = require("./Navigation.bs.js");

var component = ReasonReact.statelessComponent("Page");

function show(prim) {
  return prim;
}

var summary = React.createElement("div", {
      className: "parallax-container",
      id: "index-banner"
    }, React.createElement("div", {
          className: "section no-pad-bot"
        }, React.createElement("div", {
              className: "container"
            }, React.createElement("br", undefined), React.createElement("h1", {
                  className: "header center text-lighten-2"
                }, "Steven Thomas"), React.createElement("div", {
                  className: "row center"
                }, React.createElement("h5", {
                      className: "header col s12 light"
                    }, "Graduate of Georgia Institute of Technology. Golang Enthusiast.")))), React.createElement("div", {
          className: "parallax"
        }, React.createElement("img", {
              alt: "Unsplashed background img 1",
              src: "/assets/img/background1.jpg"
            })));

var about = React.createElement("div", {
      className: "container",
      id: "about"
    }, React.createElement("div", {
          className: "section"
        }, React.createElement("div", {
              className: "row"
            }, React.createElement("div", {
                  className: "col s12 m6"
                }, React.createElement("div", {
                      className: "icon-block"
                    }, React.createElement("h2", {
                          className: "center brown-text"
                        }, React.createElement("i", {
                              className: "material-icons"
                            }, "account_circle")), React.createElement("h5", {
                          className: "center"
                        }, "About me"), React.createElement("p", {
                          className: "light"
                        }, "We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers."))), React.createElement("div", {
                  className: "col s12 m6"
                }, React.createElement("div", {
                      className: "icon-block"
                    }, React.createElement("h2", {
                          className: "center brown-text"
                        }, React.createElement("i", {
                              className: "material-icons"
                            }, "web")), React.createElement("h5", {
                          className: "center"
                        }, "About this site"), React.createElement("p", {
                          className: "light"
                        }, "By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience."))))));

var contact = React.createElement("div", {
      className: "container"
    }, React.createElement("div", {
          className: "section"
        }, React.createElement("div", {
              className: "row"
            }, React.createElement("div", {
                  className: "col s12 center"
                }, React.createElement("h3", undefined, React.createElement("i", {
                          className: "mdi-content-send brown-text"
                        })), React.createElement("h4", undefined, "Contact Us"), React.createElement("p", {
                      className: "left-align light"
                    }, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;")))));

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, Navigation$ReactTemplate.render, summary, about, React.createElement("div", {
                      className: "parallax-container valign-wrapper"
                    }, React.createElement("div", {
                          className: "section no-pad-bot"
                        }, React.createElement("div", {
                              className: "container"
                            }, React.createElement("div", {
                                  className: "row center"
                                }, React.createElement("h5", {
                                      className: "header col s12 light"
                                    }, "A modern responsive front-end framework based on Material Design")))), React.createElement("div", {
                          className: "parallax"
                        }, React.createElement("img", {
                              alt: "Unsplashed background img 2",
                              src: "/assets/img/background2.jpg"
                            }))), contact, React.createElement("div", {
                      className: "parallax-container valign-wrapper"
                    }, React.createElement("div", {
                          className: "section no-pad-bot"
                        }, React.createElement("div", {
                              className: "container"
                            }, React.createElement("div", {
                                  className: "row center"
                                }, React.createElement("h5", {
                                      className: "header col s12 light"
                                    }, "A modern responsive front-end framework based on Material Design")))), React.createElement("div", {
                          className: "parallax"
                        }, React.createElement("img", {
                              alt: "Unsplashed background img 3",
                              src: "/assets/img/background3.jpg"
                            }))), Footer$ReactTemplate.render);
    });
  return newrecord;
}

exports.component = component;
exports.show = show;
exports.summary = summary;
exports.about = about;
exports.contact = contact;
exports.make = make;
/* component Not a pure module */
