// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Home$ReactTemplate = require("./Home.bs.js");
var Director = require("director/build/director");

var router = new Director.Router({
      "/": ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Home$ReactTemplate.make(/* array */[])), "index")
    });

router.configure({
      html5history: /* true */1
    });

router.init("/");

exports.router = router;
/* router Not a pure module */
