// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function show(prim) {
  return prim;
}

var dataActivates = React.cloneElement(React.createElement("a", {
          className: "button-collapse",
          href: "#"
        }, React.createElement("i", {
              className: "material-icons"
            }, "menu")), {
      "data-activates": "nav-mobile"
    });

function navbarLinks(elements) {
  return /* array */[
          React.createElement("ul", {
                className: "right hide-on-med-and-down"
              }, elements),
          React.createElement("ul", {
                className: "side-nav",
                id: "nav-mobile"
              }, elements)
        ];
}

function navbarLink(text, href) {
  return React.createElement("li", undefined, React.createElement("a", {
                  href: href
                }, text));
}

var render = React.createElement("nav", {
      className: "white",
      role: "navigation"
    }, React.createElement("div", {
          className: "nav-wrapper container"
        }, React.createElement("a", {
              className: "dark-font",
              id: "logo-container",
              href: "#"
            }, "Steven Thomas"), navbarLinks(/* array */[
              navbarLink("About", "#about"),
              navbarLink("Projects", "#projects")
            ]), dataActivates));

exports.show = show;
exports.dataActivates = dataActivates;
exports.navbarLinks = navbarLinks;
exports.navbarLink = navbarLink;
exports.render = render;
/* dataActivates Not a pure module */
