// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Shared$ReactTemplate = require("./Shared.bs.js");

var semantics = React.createElement("div", {
      className: "card teal"
    }, React.createElement("div", {
          className: "card-content white-text"
        }, React.createElement("h5", undefined, Shared$ReactTemplate.show("Semantics")), React.createElement("p", {
              className: "light"
            }, Shared$ReactTemplate.show("This will be project 1"))));

var concur = React.createElement("div", {
      className: "card teal"
    }, React.createElement("div", {
          className: "card-content white-text"
        }, React.createElement("h5", undefined, Shared$ReactTemplate.show("Concur")), React.createElement("p", {
              className: "light"
            }, Shared$ReactTemplate.show("This will be project 2"))));

var show = Shared$ReactTemplate.show;

var bold = Shared$ReactTemplate.bold;

var negTopMargin = Shared$ReactTemplate.negTopMargin;

var link = Shared$ReactTemplate.link;

var $plus$plus$plus = Shared$ReactTemplate.$plus$plus$plus;

exports.show = show;
exports.bold = bold;
exports.negTopMargin = negTopMargin;
exports.link = link;
exports.$plus$plus$plus = $plus$plus$plus;
exports.semantics = semantics;
exports.concur = concur;
/* semantics Not a pure module */
