// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Shared$ReactTemplate = require("./Shared.bs.js");

function card(title, description, link) {
  return React.createElement("div", {
              className: "card blue-grey"
            }, React.createElement("div", {
                  className: "card-content white-text"
                }, React.createElement("h5", undefined, Shared$ReactTemplate.show(title)), React.createElement("p", {
                      className: "light"
                    }, Shared$ReactTemplate.show(description))), React.createElement("div", {
                  className: "card-action"
                }, link));
}

var semantics = card("Semantics", "A CLI tool built using Golang to automatically manage semantic versioning of projects.", Shared$ReactTemplate.link("Find it on GitHub", "https://github.com/stevenmatthewt/semantics"));

var concur = card("Concur", "A Golang package to facilitate with Go concurrency.", Shared$ReactTemplate.link("Find it on GitHub", "https://github.com/stevenmatthewt/concur"));

var dotfiles = card("Dotfiles", "My personal dotfiles used to setup my computers.", Shared$ReactTemplate.link("Find it on GitHub", "https://github.com/stevenmatthewt/dotfiles"));

var template = card("Tmpl", "A Golang CLI tool to generate projects based off of templates.", Shared$ReactTemplate.link("Find it on GitHub", "https://github.com/stevenmatthewt/template"));

var show = Shared$ReactTemplate.show;

var bold = Shared$ReactTemplate.bold;

var negTopMargin = Shared$ReactTemplate.negTopMargin;

var link = Shared$ReactTemplate.link;

var $plus$plus$plus = Shared$ReactTemplate.$plus$plus$plus;

exports.show = show;
exports.bold = bold;
exports.negTopMargin = negTopMargin;
exports.link = link;
exports.$plus$plus$plus = $plus$plus$plus;
exports.card = card;
exports.semantics = semantics;
exports.concur = concur;
exports.dotfiles = dotfiles;
exports.template = template;
/* semantics Not a pure module */
