// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function show(prim) {
  return prim;
}

function bold(text) {
  return React.createElement("span", {
              className: "bold"
            }, text);
}

var negTopMargin = {
  marginTop: "-0.8em"
};

function link(text, href) {
  return React.createElement("a", {
              href: href
            }, text);
}

function $plus$plus$plus(a, b) {
  return /* array */[
          a,
          b
        ];
}

exports.show = show;
exports.bold = bold;
exports.negTopMargin = negTopMargin;
exports.link = link;
exports.$plus$plus$plus = $plus$plus$plus;
/* react Not a pure module */
